name: Run benchmarks

on: [push, pull_request]

jobs:

  benchmarks:

    runs-on: ubuntu-20.04

    steps:

      - name: Checkout SymPy Benchmarks
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv asv packaging

      - name: Configure benchmarks
        run: asv machine --yes --config asv.conf.actions.json

      - name: Run benchmarks
        run: asv run --config asv.conf.actions.json
